export const GET_POST_DATA = 'GET_POST_DATA';
export const GET_POST_DATA_SUCCESS = 'GET_POST_DATA_SUCCESS';
export const GET_POST_DATA_ERROR = 'GET_POST_DATA_ERROR';
export const SET_AFTER = 'SET_AFTER';
export const SET_LOAD_MORE = 'SET_LOAD_MORE';
